require: rubocop-rails
Style/Documentation:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/IndexWith:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  Exclude:
    - node_modules/**/*
    - bin/**
    - spec/dummy/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - lib/tasks/auto_annotate_models.rake

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - db/migrate/*

Layout/LineLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*
    - db/migrate/*
